pull_request_rules:
   - name: Blocking PR if missing a related issue or PR doesn't have kind/improvement label
      conditions:
        - or:
            - -body~=\#[0-9]{1,6}(\s+|$)
            - -body~=https://github.com/zilliztech/Knowhere/issues/[0-9]{1,6}(\s+|$)
      actions:
        label:
          add:
            - do-not-merge/missing-related-issue
        comment:
          message: |
            @{{author}} 🔍 Important: PR Classification Needed!

            For efficient project management and a seamless review process, it's essential to classify your PR correctly. Here's how:

            1. If you're fixing a bug, label it as kind/bug.
            2. For small tweaks (less than 20 lines without altering any functionality), please use kind/improvement.
            3. Significant changes that don't modify existing functionalities should be tagged as kind/enhancement.
            4. Adjusting APIs or changing functionality? Go with kind/feature.

            For any PR outside the kind/improvement category, ensure you link to the associated issue using the format: “issue: #<issue-number>”.

            Thanks for your efforts and contribution to the community!.



  - name: Dismiss block label if related issue be added into PR
    conditions:
          - or:
            - body~=\#[0-9]{1,6}(\s+|$)
            - body~=https://github.com/zilliztech/Knowhere/issues/[0-9]{1,6}(\s+|$)
    actions:
      label:
        remove:
          - do-not-merge/missing-related-issue
