apiVersion: v1
kind: Pod
metadata:
  labels:
    beta.kubernetes.io/arch: arm64
  namespace: knowhere-ci
spec:
  enableServiceLinks: false
  nodeSelector:
    app: knowhere-e2e
  tolerations:
    - key: node-role.kubernetes.io/knowhere
      operator: Exists
      effect: NoSchedule
  containers:
  - name: main
    image: milvusdb/knowhere-cpu-build:arm64-ubuntu22.04-20250219-5f3afcd8
    tty: true
    args: ["cat"]
    resources:
      requests:
        memory: "16Gi"
        cpu: "4"
      limits:
        memory: "16Gi"
        cpu: "4"
    volumeMounts:
      - mountPath: /home/data
        name: db-data
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: db-data
