name: Analyzer

on:
  pull_request:
  push:
    branches: [main]

jobs:
  analyzer:
    name: analyzer
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'none'
      - name: Restore Cache
        uses: ./.github/actions/cache-restore
        with:
          os: ubuntu-22.04
      - name: Install Dependency
        run: |
          sudo apt update && sudo apt install -y cmake g++ gcc libopenblas-openmp-dev libaio-dev libcurl4-openssl-dev libevent-dev clang-tidy-14 python3-pip libomp-dev ccache && \
          pip3 install conan==1.61.0 && (conan remote add default-conan-local https://milvus01.jfrog.io/artifactory/api/conan/default-conan-local || true)
      - name: Build & Analyzer
        run: |
          mkdir build && cd build && conan install .. --build=missing -o with_ut=True -o with_diskann=True -s compiler.libcxx=libstdc++11 && conan build .. \
          && cd .. && find src -type f | grep -E "\.cc$" | xargs /usr/bin/run-clang-tidy-14.py -quiet -p=./build/Release
      - name: Save Cache
        uses: ./.github/actions/cache-save
        with:
          os: ubuntu-22.04
