name: Analyzer

on:
  pull_request:
  push:

jobs:
  analyzer:
    name: analyzer
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependency
        run: |
          sudo apt update && sudo apt install -y cmake g++ gcc libopenblas-dev libaio-dev libcurl4-openssl-dev libevent-dev clang-tidy python3-pip && \
          pip3 install conan==1.61.0 && conan remote add default-conan-local https://milvus01.jfrog.io/artifactory/api/conan/default-conan-local
      - name: Cache conan
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ hashFiles('**/conanfile.py') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/conanfile.py') }}
      - name: Build & Analyzer
        run: |
          mkdir build && cd build && conan install .. --build=missing -o with_ut=True -o with_diskann=True && cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DISKANN=ON  \
          && cd .. && find src -type f | grep -E "\.cc$" | xargs /usr/lib/llvm-10/share/clang/run-clang-tidy.py -quiet -p=./build
